# Generated by Django 3.0.4 on 2020-06-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200530_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimeProduct',
        ),
    ]
